### ISSUE TITLE
not support Android N

### ISSUE THREAD

**Issue by imknown** [TeamWin/android_device_lge_bullhead#3]
is there one preview for Android N?

**Comment by PedroMCostaAndrade** [comment]
the only one that works is before 3.0 version, try it.. but they have the bug on decrypt if you don't bother to make the workarounds to make it work you could use it.. 
the 3.0 versions install but when we enter on recovery mode it doesn't load, it stays on the logo image...

**Comment by imknown** [comment]
Thx, i've downgraded to Android 6.0.1 using TWRP 3.0.2-0.
I use AVD for developing only now time. :+1:

**Comment by PedroMCostaAndrade** [comment]
someone could help with this?

**Comment by imknown** [comment]
Does [this](https://github.com/TeamWin/android_device_lge_bullhead/commit/e110ef62dce8c2ed9112d12a22480a41509afc3d) help us?

Update:
I tried this version `twrp-3.0.2-1-bullhead.img`, and it can go into TWRP now.
